export interface Pattern {
  id: string;
  title: string;
  label: string;
  desc: string;
  useWhen: string;
  triggers: string[];
  outcome: string;
  complexity: string;
  category: string;
  categoryLabel: string;
  accent: string;
  icon: string;
  examples: string[];
}

export const AUTOMATION_PATTERNS: Pattern[] = [
  {
    id: "AP1",
    title: "The Data Extraction Pipeline",
    label: "DATA_EXTRACTION",
    desc: "Automatically pulls data from unstructured sources (PDFs, emails, images) and structures it for your systems.",
    useWhen: "Your team spends hours manually copying data from documents into spreadsheets or CRMs.",
    triggers: ["manual data entry", "invoice processing", "copy-pasting from emails", "document parsing"],
    outcome: "Eliminates manual entry, reduces errors to near-zero, and frees up human capital for high-value tasks.",
    complexity: "Low",
    category: "data",
    categoryLabel: "Data & Intel",
    accent: "#3b82f6",
    icon: "📄",
    examples: ["We get 500 invoices a month and someone has to type them into Quickbooks.", "Sales reps spend 2 hours a day logging email notes into Salesforce."]
  },
  {
    id: "AP2",
    title: "The Intelligent Routing System",
    label: "ROUTING_ENGINE",
    desc: "Analyzes incoming requests (tickets, emails, leads) and automatically routes them to the correct department or individual based on content, sentiment, and rules.",
    useWhen: "You have a central inbox or ticketing system that requires a human to read and assign every item.",
    triggers: ["triage", "ticket assignment", "lead distribution", "inbox management"],
    outcome: "Instantaneous routing, faster response times, and no bottlenecks at the triage stage.",
    complexity: "Medium",
    category: "workflow",
    categoryLabel: "Workflow",
    accent: "#8b5cf6",
    icon: "🔀",
    examples: ["Our support manager spends half her day just assigning Zendesk tickets.", "Leads sit in a general inbox for hours before a sales rep claims them."]
  },
  {
    id: "AP3",
    title: "The Automated Onboarding Flow",
    label: "ONBOARDING_SEQ",
    desc: "A multi-step, conditional sequence that handles all administrative tasks when a new client or employee joins.",
    useWhen: "Onboarding requires multiple manual steps across different software platforms (creating accounts, sending welcome emails, setting up folders).",
    triggers: ["new hire setup", "client onboarding", "account provisioning", "welcome sequence"],
    outcome: "A flawless, instant onboarding experience that requires zero administrative effort.",
    complexity: "Medium",
    category: "operations",
    categoryLabel: "Operations",
    accent: "#10b981",
    icon: "🚀",
    examples: ["When we sign a client, I have to create a Slack channel, a Google Drive folder, and send 3 different emails.", "IT takes 2 days to provision software for new hires."]
  },
  {
    id: "AP4",
    title: "The Sentiment & Response Engine",
    label: "SENTIMENT_AI",
    desc: "Monitors communications, gauges the emotional tone (angry, urgent, happy), and either drafts a response or escalates immediately.",
    useWhen: "You need to prioritize urgent or angry customer communications but have too much volume to read everything instantly.",
    triggers: ["customer complaints", "social media monitoring", "urgent escalations", "review management"],
    outcome: "Prevents churn by instantly catching and addressing negative experiences before they escalate.",
    complexity: "High",
    category: "customer",
    categoryLabel: "Customer",
    accent: "#f59e0b",
    icon: "🎭",
    examples: ["We missed an angry email from our biggest client because it was buried under 50 routine requests.", "We want to automatically reply to 5-star reviews and flag 1-star reviews to management."]
  },
  {
    id: "AP5",
    title: "The Sync & Reconcile Loop",
    label: "DATA_SYNC",
    desc: "Ensures that when data changes in System A, it is instantly and accurately reflected in System B and System C.",
    useWhen: "You use multiple software platforms that don't talk to each other natively, leading to mismatched data.",
    triggers: ["data silos", "inconsistent records", "double entry", "system integration"],
    outcome: "A single source of truth across your entire tech stack, eliminating confusion and manual updates.",
    complexity: "Medium",
    category: "data",
    categoryLabel: "Data & Intel",
    accent: "#06b6d4",
    icon: "🔄",
    examples: ["When a deal closes in HubSpot, we have to manually create the project in Asana and the client in Stripe.", "Our inventory in Shopify doesn't match our warehouse software."]
  },
  {
    id: "AP6",
    title: "The Predictive Alert System",
    label: "PREDICTIVE_ALERT",
    desc: "Monitors data trends and sends proactive alerts *before* a threshold is crossed or a problem occurs.",
    useWhen: "You are constantly reacting to problems (low inventory, budget overruns, server downtime) instead of preventing them.",
    triggers: ["inventory stockouts", "budget tracking", "SLA breaches", "performance monitoring"],
    outcome: "Shifts your operations from reactive to proactive, saving money and preserving client trust.",
    complexity: "High",
    category: "operations",
    categoryLabel: "Operations",
    accent: "#ef4444",
    icon: "⚠️",
    examples: ["We only know we're out of stock when a customer tries to buy and can't.", "We keep accidentally going over our monthly ad spend budget."]
  }
];

export const ANALYTICS_PATTERNS: Pattern[] = [
  {
    id: "DA1",
    title: "Trend & Forecasting Engine",
    label: "TREND_ANALYSIS",
    desc: "Analyzes historical data to identify underlying trends and projects future performance using statistical and machine learning models.",
    useWhen: "You need to anticipate future demand, revenue, or resource requirements based on past behavior.",
    triggers: ["sales forecasting", "demand planning", "budget projection", "seasonality analysis"],
    outcome: "Accurate predictions that allow for proactive resource allocation and strategic planning.",
    complexity: "High",
    category: "prediction",
    categoryLabel: "Prediction",
    accent: "#8b5cf6",
    icon: "📈",
    examples: ["We need to know how much inventory to order for Q4 based on the last 3 years of data.", "We want to predict next month's MRR based on current pipeline velocity."]
  },
  {
    id: "DA2",
    title: "Cohort Retention Analysis",
    label: "COHORT_ANALYSIS",
    desc: "Groups users by shared characteristics (usually sign-up date) to track behavior, engagement, and retention over time.",
    useWhen: "You need to understand if recent product changes or marketing campaigns are improving long-term user retention.",
    triggers: ["churn analysis", "user retention", "LTV calculation", "feature adoption"],
    outcome: "Clear visibility into which user groups are sticking around and which are churning, enabling targeted interventions.",
    complexity: "Medium",
    category: "customer",
    categoryLabel: "Customer",
    accent: "#ec4899",
    icon: "👥",
    examples: ["Are users who signed up during our Black Friday sale retaining as well as our organic users?", "Did the new onboarding flow we launched in March actually reduce month-1 churn?"]
  },
  {
    id: "DA3",
    title: "Predictive Scoring Model",
    label: "PREDICTIVE_MODEL",
    desc: "Assigns a probability score to individual entities (leads, customers, transactions) indicating the likelihood of a specific future action.",
    useWhen: "You need to prioritize sales efforts, identify churn risks before they happen, or flag potentially fraudulent transactions.",
    triggers: ["lead scoring", "churn prediction", "fraud detection", "upsell targeting"],
    outcome: "Focuses human effort and automated systems on the highest-leverage opportunities or highest-risk threats.",
    complexity: "High",
    category: "prediction",
    categoryLabel: "Prediction",
    accent: "#f59e0b",
    icon: "🎯",
    examples: ["Sales is wasting time on bad leads; we need a model to score leads based on their likelihood to close.", "We want to identify which current customers have a >70% probability of churning in the next 30 days."]
  },
  {
    id: "DA4",
    title: "Live Event Stream Analytics",
    label: "REAL_TIME_STREAM",
    desc: "Processes and analyzes data continuously as it is generated, providing sub-second insights into current system or user state.",
    useWhen: "Decisions must be made instantly based on current conditions, such as dynamic pricing, live monitoring, or immediate personalization.",
    triggers: ["real-time dashboards", "live monitoring", "dynamic pricing", "instant personalization"],
    outcome: "Immediate awareness of critical events, enabling instantaneous automated or human response.",
    complexity: "High",
    category: "realtime",
    categoryLabel: "Real-Time",
    accent: "#06b6d4",
    icon: "⚡",
    examples: ["We need to monitor server health and automatically scale resources the second a traffic spike hits.", "We want to change product recommendations on the homepage based on the user's clicks in their current session."]
  },
  {
    id: "DA5",
    title: "Conversion Funnel Intelligence",
    label: "FUNNEL_ANALYTICS",
    desc: "Maps the exact step-by-step journey users take toward a goal, identifying precisely where drop-offs occur.",
    useWhen: "You have a multi-step process (checkout, onboarding, signup) and need to optimize the conversion rate.",
    triggers: ["checkout optimization", "onboarding drop-off", "conversion rate optimization", "user journey mapping"],
    outcome: "Pinpoints the exact bottlenecks in your user journey, providing clear targets for UX/UI improvements.",
    complexity: "Medium",
    category: "customer",
    categoryLabel: "Customer",
    accent: "#10b981",
    icon: "🔻",
    examples: ["We have a lot of traffic to the pricing page, but very few signups. Where are we losing them?", "What percentage of users who add an item to their cart actually complete the purchase?"]
  },
  {
    id: "DA6",
    title: "AI Customer Segmentation",
    label: "SEGMENTATION",
    desc: "Uses clustering algorithms to automatically group customers based on complex behavioral, demographic, and transactional patterns.",
    useWhen: "Rule-based segmentation (e.g., 'users in California') is no longer sufficient, and you need to discover hidden personas.",
    triggers: ["personalized marketing", "persona discovery", "RFM analysis", "targeted campaigns"],
    outcome: "Discovers nuanced customer segments you didn't know existed, enabling hyper-personalized marketing and product experiences.",
    complexity: "High",
    category: "customer",
    categoryLabel: "Customer",
    accent: "#6366f1",
    icon: "🧩",
    examples: ["We want to move beyond basic demographics and group our users by their actual usage patterns and buying behavior.", "Can we identify the 'power users' who are most likely to advocate for our brand?"]
  },
  {
    id: "DA7",
    title: "Intelligent Anomaly Detection",
    label: "ANOMALY_DETECTION",
    desc: "Establishes a baseline of normal behavior and automatically flags statistically significant deviations in real-time.",
    useWhen: "You have too many metrics to monitor manually and need to be alerted only when something truly unusual happens.",
    triggers: ["fraud detection", "system outages", "sudden traffic drops", "data quality alerts"],
    outcome: "Reduces alert fatigue by only notifying you of genuine issues, while catching critical problems humans might miss.",
    complexity: "High",
    category: "realtime",
    categoryLabel: "Real-Time",
    accent: "#ef4444",
    icon: "🚨",
    examples: ["Alert us immediately if the checkout success rate drops by more than 2 standard deviations from the historical norm.", "Flag any transactions that exhibit patterns typical of fraudulent activity."]
  },
  {
    id: "DA8",
    title: "Multi-Touch Attribution Engine",
    label: "ATTRIBUTION",
    desc: "Assigns fractional credit to all marketing touchpoints a user interacted with before converting, rather than just the first or last click.",
    useWhen: "You run campaigns across multiple channels (ads, email, social, organic) and need to know the true ROI of each.",
    triggers: ["marketing ROI", "channel optimization", "ad spend allocation", "customer journey"],
    outcome: "Provides a realistic view of how different marketing channels work together to drive conversions, optimizing ad spend.",
    complexity: "High",
    category: "insight",
    categoryLabel: "Insight",
    accent: "#f43f5e",
    icon: "🔗",
    examples: ["If a user clicks a Facebook ad, reads a blog post, and then converts via an email newsletter, which channel gets the credit?", "We need to justify our spend on top-of-funnel brand awareness campaigns."]
  },
  {
    id: "DA9",
    title: "Automated Data Quality Engine",
    label: "DATA_QUALITY",
    desc: "Continuously scans databases and pipelines to identify, flag, and automatically correct missing, inconsistent, or erroneous data.",
    useWhen: "Your analytics and machine learning models are suffering because the underlying data is messy or unreliable.",
    triggers: ["data cleansing", "ETL monitoring", "duplicate resolution", "schema validation"],
    outcome: "Ensures high trust in data across the organization, preventing 'garbage in, garbage out' scenarios.",
    complexity: "Medium",
    category: "ops",
    categoryLabel: "Operations",
    accent: "#14b8a6",
    icon: "🧹",
    examples: ["We have thousands of duplicate customer records in Salesforce that need to be merged.", "We need to ensure that every new product entry has a valid SKU format before it enters the database."]
  },
  {
    id: "DA10",
    title: "AI Executive Intelligence Reports",
    label: "EXECUTIVE_REPORTING",
    desc: "Automatically synthesizes data from multiple dashboards into natural language summaries highlighting key takeaways and recommended actions.",
    useWhen: "Leadership needs the 'so what' from the data without having to dig through complex charts and tables.",
    triggers: ["board reporting", "automated insights", "NLG (Natural Language Generation)", "KPI summaries"],
    outcome: "Saves hours of manual reporting time and ensures decision-makers get clear, actionable insights instantly.",
    complexity: "Medium",
    category: "insight",
    categoryLabel: "Insight",
    accent: "#8b5cf6",
    icon: "📊",
    examples: ["Generate a weekly summary email for the CEO explaining why revenue was up or down, citing the specific drivers.", "Translate our complex marketing dashboard into a 3-bullet-point summary for the board meeting."]
  },
  {
    id: "DA11",
    title: "Product Usage Intelligence",
    label: "PRODUCT_ANALYTICS",
    desc: "Tracks how users interact with specific features within a software product to inform roadmap decisions.",
    useWhen: "You need to know which features drive value, which are ignored, and where users experience friction.",
    triggers: ["feature adoption", "UX optimization", "roadmap planning", "time-to-value"],
    outcome: "Data-driven product development that focuses engineering resources on the features that actually drive retention and revenue.",
    complexity: "Medium",
    category: "insight",
    categoryLabel: "Insight",
    accent: "#3b82f6",
    icon: "📱",
    examples: ["Are users actually using the new 'export to PDF' feature we spent a month building?", "How long does it take a new user to reach the 'aha moment' in our app?"]
  },
  {
    id: "DA12",
    title: "Competitive Intelligence Radar",
    label: "COMPETITIVE_INTEL",
    desc: "Automated scraping and analysis of competitor pricing, features, reviews, and market positioning.",
    useWhen: "You operate in a highly competitive market and need to react quickly to competitor moves.",
    triggers: ["price monitoring", "sentiment analysis", "market positioning", "competitor tracking"],
    outcome: "Maintains a strategic advantage by ensuring you are never blindsided by a competitor's pricing change or new feature launch.",
    complexity: "High",
    category: "prediction",
    categoryLabel: "Prediction",
    accent: "#f97316",
    icon: "📡",
    examples: ["Alert us immediately if a key competitor drops their price below our baseline.", "Analyze all public reviews of our top 3 competitors to identify their most common weaknesses."]
  },
  {
    id: "DA13",
    title: "Operations Intelligence Layer",
    label: "OPERATIONAL_KPIs",
    desc: "Aggregates data from HR, finance, supply chain, and IT to provide a holistic view of internal company health and efficiency.",
    useWhen: "Company operations are siloed, making it difficult to see how inefficiencies in one department affect another.",
    triggers: ["supply chain visibility", "resource allocation", "cost optimization", "capacity planning"],
    outcome: "Identifies hidden inefficiencies and bottlenecks across the entire organizational value chain.",
    complexity: "High",
    category: "ops",
    categoryLabel: "Operations",
    accent: "#64748b",
    icon: "⚙️",
    examples: ["How does employee turnover in the warehouse correlate with order fulfillment delays?", "We need a unified view of our cloud infrastructure costs versus our actual usage."]
  },
  {
    id: "DA14",
    title: "Dynamic Pricing Analytics",
    label: "PRICING_INTELLIGENCE",
    desc: "Uses algorithms to adjust prices in real-time based on demand, inventory levels, competitor pricing, and customer behavior.",
    useWhen: "You have a large catalog of products or services and fixed pricing is leaving money on the table.",
    triggers: ["yield management", "surge pricing", "margin optimization", "inventory clearing"],
    outcome: "Maximizes revenue and profit margins automatically by finding the optimal price point for every transaction.",
    complexity: "High",
    category: "prediction",
    categoryLabel: "Prediction",
    accent: "#10b981",
    icon: "💲",
    examples: ["Automatically lower the price of seasonal inventory as we approach the end of the season to clear stock.", "Increase pricing on our SaaS platform dynamically based on the user's perceived value and usage tier."]
  },
  {
    id: "DA15",
    title: "Unstructured Data Intelligence",
    label: "NLP_ANALYTICS",
    desc: "Applies Natural Language Processing (NLP) and computer vision to extract structured insights from text, audio, and images.",
    useWhen: "You have massive amounts of qualitative data (support tickets, sales calls, reviews) that are impossible to analyze manually.",
    triggers: ["call transcription analysis", "document parsing", "sentiment extraction", "image recognition"],
    outcome: "Unlocks the hidden value in your unstructured data, turning conversations and documents into quantifiable metrics.",
    complexity: "High",
    category: "insight",
    categoryLabel: "Insight",
    accent: "#8b5cf6",
    icon: "🧠",
    examples: ["Analyze 10,000 customer support transcripts to identify the top 5 reasons people are requesting refunds.", "Automatically scan uploaded receipts to extract the merchant name, date, and total amount."]
  }
];

export const FORESIGHT_TOOLS: Pattern[] = [
  {
    id: "F01",
    title: "Horizon Scanning System",
    label: "SCANNING",
    desc: "Continuous, automated monitoring of weak signals, emerging trends, and technological breakthroughs across peripheral industries.",
    useWhen: "You need early warning of disruptions before they hit the mainstream market.",
    triggers: ["trend monitoring", "weak signals", "emerging tech", "market shifts"],
    outcome: "Prevents strategic surprises and identifies first-mover opportunities 12-36 months ahead of competitors.",
    complexity: "Medium",
    category: "signals",
    categoryLabel: "Signals",
    accent: "#3b82f6",
    icon: "🔭",
    examples: ["Track patent filings in adjacent industries to predict new product categories.", "Monitor academic papers for breakthroughs in materials science relevant to our supply chain."]
  },
  {
    id: "F02",
    title: "Scenario Planning Matrix",
    label: "SCENARIOS",
    desc: "Development of multiple plausible future environments based on critical uncertainties, allowing for robust strategy testing.",
    useWhen: "The future is highly uncertain and a single 'official future' strategy is too risky.",
    triggers: ["strategic planning", "risk mitigation", "uncertainty mapping", "future casting"],
    outcome: "Creates a highly resilient strategy that succeeds across multiple different future states.",
    complexity: "High",
    category: "strategy",
    categoryLabel: "Strategy",
    accent: "#8b5cf6",
    icon: "🗺️",
    examples: ["What is our strategy if AI commoditizes our core service AND regulatory changes restrict our data access?", "How do we pivot if supply chain costs increase by 300% over the next 5 years?"]
  },
  {
    id: "F03",
    title: "Strategic Roadmapping",
    label: "PLANNING",
    desc: "Visual alignment of long-term strategic goals with the specific technological, market, and organizational milestones required to achieve them.",
    useWhen: "You have a vision for the future but lack a clear, sequenced path connecting today's actions to tomorrow's goals.",
    triggers: ["technology roadmap", "product strategy", "capability mapping", "milestone planning"],
    outcome: "Transforms abstract vision into an executable, time-bound plan with clear dependencies.",
    complexity: "Medium",
    category: "strategy",
    categoryLabel: "Strategy",
    accent: "#10b981",
    icon: "🛣️",
    examples: ["Map the specific AI capabilities we need to build internally over the next 3 years to launch our autonomous product line.", "Align our R&D investments with projected shifts in consumer behavior for 2030."]
  },
  {
    id: "F04",
    title: "Competitive Intelligence Radar",
    label: "COMPETITION",
    desc: "Systematic tracking and analysis of competitor movements, investments, and strategic pivots to anticipate their future positioning.",
    useWhen: "You operate in a dynamic market where competitors are rapidly evolving or non-traditional competitors are entering.",
    triggers: ["competitor tracking", "market positioning", "threat assessment", "M&A monitoring"],
    outcome: "Ensures you are never blindsided by a competitor's strategic move and can proactively counter their positioning.",
    complexity: "Medium",
    category: "signals",
    categoryLabel: "Signals",
    accent: "#f59e0b",
    icon: "📡",
    examples: ["Monitor the hiring patterns of our top 3 competitors to deduce their upcoming product focus.", "Track startup funding in our sector to identify potential disruptive threats early."]
  },
  {
    id: "F05",
    title: "Technology Adoption Curve",
    label: "TECH",
    desc: "Mapping emerging technologies against their maturity, hype cycle, and specific relevance to your business model.",
    useWhen: "You need to decide *when* to invest in a new technology (e.g., Generative AI, Web3) vs. when to wait.",
    triggers: ["tech scouting", "investment timing", "hype cycle analysis", "R&D prioritization"],
    outcome: "Optimizes technology investments, avoiding the 'bleeding edge' trap while preventing technological obsolescence.",
    complexity: "Medium",
    category: "tech",
    categoryLabel: "Technology",
    accent: "#06b6d4",
    icon: "📈",
    examples: ["Determine if spatial computing is mature enough for enterprise deployment in our training division.", "Assess the readiness of quantum cryptography for our long-term data security strategy."]
  },
  {
    id: "F06",
    title: "Megatrend Impact Analysis",
    label: "MACRO",
    desc: "Evaluating how massive, slow-moving global shifts (demographics, climate, urbanization) will intersect with your specific business model.",
    useWhen: "You are doing long-range planning (5-10+ years) and need to understand the macro forces shaping your future market.",
    triggers: ["long-term planning", "macroeconomics", "demographic shifts", "climate impact"],
    outcome: "Aligns your long-term strategy with unstoppable global forces, turning macro threats into tailwinds.",
    complexity: "High",
    category: "macro",
    categoryLabel: "Macro",
    accent: "#ec4899",
    icon: "🌍",
    examples: ["How will the aging population in our primary markets affect demand for our current product suite by 2035?", "What is the impact of global supply chain regionalization on our manufacturing strategy?"]
  },
  {
    id: "F07",
    title: "Disruption Vulnerability Index",
    label: "RISK",
    desc: "A systematic stress-test of your current business model to identify critical dependencies and areas vulnerable to technological or market disruption.",
    useWhen: "Your business model has been highly successful but relies on assumptions that may no longer hold true in the near future.",
    triggers: ["stress testing", "business model innovation", "risk assessment", "antifragility"],
    outcome: "Highlights structural weaknesses before competitors exploit them, enabling proactive business model evolution.",
    complexity: "High",
    category: "risk",
    categoryLabel: "Risk",
    accent: "#ef4444",
    icon: "🛡️",
    examples: ["Identify which of our revenue streams would go to zero if open-source AI models match our proprietary tech.", "Assess our vulnerability to a sudden shift in consumer data privacy regulations."]
  },
  {
    id: "F08",
    title: "Weak Signal Detection",
    label: "SIGNALS",
    desc: "The process of identifying anomalous data points, fringe behaviors, or early innovations that hint at massive future shifts.",
    useWhen: "You want to spot the 'next big thing' before it becomes obvious to the rest of the market.",
    triggers: ["innovation scouting", "fringe analysis", "early adoption", "trend spotting"],
    outcome: "Provides the ultimate first-mover advantage by acting on signals while competitors are still waiting for trends.",
    complexity: "High",
    category: "signals",
    categoryLabel: "Signals",
    accent: "#8b5cf6",
    icon: "🔍",
    examples: ["Noticing a niche behavior among Gen Z users on a new social platform that could redefine e-commerce.", "Identifying a novel use-case for our product in an industry we don't currently target."]
  },
  {
    id: "F09",
    title: "Strategic Options Portfolio",
    label: "STRATEGY",
    desc: "Developing a portfolio of small, calculated bets (experiments, partnerships, R&D) that provide the 'option' to scale if a specific future materializes.",
    useWhen: "You face high uncertainty and cannot commit massive resources to a single direction, but cannot afford to do nothing.",
    triggers: ["real options", "innovation portfolio", "hedging", "agile strategy"],
    outcome: "Maximizes strategic flexibility; you buy the right to play in future markets without betting the entire company.",
    complexity: "High",
    category: "strategy",
    categoryLabel: "Strategy",
    accent: "#14b8a6",
    icon: "🗂️",
    examples: ["Investing a small amount in a blockchain startup to learn the tech, giving us the option to acquire them if the market shifts.", "Running 5 distinct product prototypes simultaneously to see which gains traction before scaling."]
  },
  {
    id: "F10",
    title: "Causal Loop Analysis",
    label: "SYSTEMS",
    desc: "Mapping the complex web of cause-and-effect relationships within your industry to understand feedback loops and unintended consequences.",
    useWhen: "You are dealing with complex, systemic problems where obvious solutions often make the problem worse.",
    triggers: ["systems thinking", "feedback loops", "complex problem solving", "policy design"],
    outcome: "Identifies the true leverage points in a system, allowing for interventions that create lasting, compounding positive change.",
    complexity: "High",
    category: "analysis",
    categoryLabel: "Analysis",
    accent: "#f43f5e",
    icon: "🔄",
    examples: ["Understanding how a price cut might temporarily boost sales but permanently degrade brand perception and long-term margin.", "Mapping the talent ecosystem to understand why increasing salaries isn't solving our retention problem."]
  },
  {
    id: "F11",
    title: "Delphi Expert Consensus",
    label: "QUALITATIVE",
    desc: "A structured communication technique that aggregates the insights of a panel of independent experts to forecast complex events.",
    useWhen: "Quantitative data is lacking or irrelevant, and you need to forecast unprecedented technological or social shifts.",
    triggers: ["expert forecasting", "consensus building", "qualitative research", "future casting"],
    outcome: "Provides highly accurate qualitative forecasts by eliminating groupthink and leveraging collective expert intuition.",
    complexity: "Medium",
    category: "analysis",
    categoryLabel: "Analysis",
    accent: "#6366f1",
    icon: "🗣️",
    examples: ["Surveying 50 leading AI researchers anonymously to predict the year AGI will be achieved.", "Gathering consensus from industry insiders on the most likely regulatory framework for autonomous vehicles."]
  },
  {
    id: "F12",
    title: "Backcasting",
    label: "FUTURES",
    desc: "Starting with a specific desired future state (e.g., 'Zero Carbon by 2040') and working backward to identify the exact steps required today to get there.",
    useWhen: "The goal is clear and ambitious, but the path from the present is obstructed by current paradigms or technological limitations.",
    triggers: ["visionary planning", "sustainability goals", "moonshots", "reverse engineering"],
    outcome: "Breaks impossible-seeming long-term goals into actionable, immediate steps, bypassing the constraints of present-day thinking.",
    complexity: "High",
    category: "strategy",
    categoryLabel: "Strategy",
    accent: "#3b82f6",
    icon: "⏪",
    examples: ["If we want to be a $1B company operating entirely on decentralized infrastructure by 2030, what must be true by 2027? By 2025? Today?", "Working backward from a fully circular economy product line to dictate today's R&D priorities."]
  },
  {
    id: "F13",
    title: "Cross-Impact Matrix",
    label: "ANALYSIS",
    desc: "An analytical tool used to evaluate how the occurrence of one future event affects the probability of other future events occurring.",
    useWhen: "You have identified multiple potential future trends or events and need to understand how they interact and compound.",
    triggers: ["probability analysis", "event interaction", "complex forecasting", "risk compounding"],
    outcome: "Reveals hidden cascades of events, showing how a seemingly isolated disruption could trigger a chain reaction across your industry.",
    complexity: "High",
    category: "analysis",
    categoryLabel: "Analysis",
    accent: "#f97316",
    icon: "✖️",
    examples: ["If universal basic income is implemented (Event A), how does that change the probability of mass automation adoption (Event B)?", "How does a breakthrough in battery tech impact the timeline for flying cars vs. grid storage?"]
  },
  {
    id: "F14",
    title: "STEEP-V Framework",
    label: "MACRO",
    desc: "A structured environmental scanning framework analyzing Social, Technological, Economic, Environmental, Political, and Values-based drivers of change.",
    useWhen: "You are conducting a comprehensive environmental scan and need to ensure no major category of disruption is overlooked.",
    triggers: ["environmental scanning", "PESTLE analysis", "macro drivers", "holistic assessment"],
    outcome: "Provides a 360-degree view of the external forces shaping your future, preventing blind spots in strategic planning.",
    complexity: "Medium",
    category: "macro",
    categoryLabel: "Macro",
    accent: "#10b981",
    icon: "🌐",
    examples: ["Using STEEP-V to analyze the future of remote work, looking beyond just the technology to consider changing social values and tax policies.", "Assessing the future of the food industry across all six dimensions simultaneously."]
  },
  {
    id: "F15",
    title: "Predictive Narrative Engine",
    label: "SYNTHESIS",
    desc: "Synthesizing complex data, trends, and scenarios into compelling, immersive stories about the future to drive organizational alignment.",
    useWhen: "You have done the foresight research, but need to communicate the vision in a way that motivates stakeholders and drives action.",
    triggers: ["science fiction prototyping", "vision communication", "change management", "storytelling"],
    outcome: "Translates abstract data into visceral, understandable futures, creating deep organizational alignment and urgency.",
    complexity: "Medium",
    category: "strategy",
    categoryLabel: "Strategy",
    accent: "#ec4899",
    icon: "📖",
    examples: ["Writing a 'day in the life' narrative of your customer in 2030 to align the product team around a new vision.", "Creating a mock news broadcast from the future to highlight the urgency of a looming competitive threat to the board."]
  }
];
